config/routes.rb
Rails.application.routes.draw do

	 root 'static_pages#home'
	 get 'browse_products' => 'products#browse_products'
	 get 'popular' => 'static_pages#popular'
	 get 'tech' => 'categories#tech'
	 get 'games' => 'categories#games'
	 get 'books' => 'categories#books'
	 get 'podcasts' => 'categories#podcasts'
	 get 'tech/popular' => 'categories#popular_tech'
	 get 'games/popular' => 'categories#popular_games'
	 get 'books/popular' => 'categories#popular_books'
	 get 'podcasts/popular' => 'categories#popular_podcasts'
	 
	 
	 devise_for :users
	 resources :products do
	 	resources :comments, only: [:new, :create, :index]
	 	member do
	 		put "upvote" => "products#upvote"
	 	end
	 end
	 

end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :title, presence: true, length: { maximum: 50 }
	validates :description, presence: true, length: { maximum: 400 }
	validates :link, presence: true, length: { maximum: 200 }
	validates :image, presence: true
	validates :product_type, presence: true
	acts_as_votable
	has_many :comments
	belongs_to :user
	
	def self.search_products(search)
  		if search
   		 where('title LIKE ? or product_type LIKE ?', "%#{search}%", "%#{search}%")
  		else
   		 all
  		end
	end	
	
	TYPES = [['Android','ANDROID'],['Chrome','CHROME'],['Web','WEB'],['Iphone','IPHONE'],
	['Slack','SLACK'],['Mac','MAC'],['Food','FOOD'],['Music','MUSIC'],
	['Hardware','HARDWARE'],['Virtual Reality','VIRTUAL REALITY'],['Email','EMAIL'],['IPad','IPAD'],
	['Windows','WINDOWS'],['Politics','POLITICS'],['Art','ART'],['Travel','TRAVEL'],
	['Music','MUSIC'],['Business','BUSINESS'],['Indie Games','INDIE GAMES'],['Occulus Rift','OCCULUS RIFT'],
	['Linux','LINUX'],['Daredevil','DAREDEVIL'],['Developer Tools','DEVELOPER TOOLS'],['Extensions','EXTENSIONS'],
	['Health and Fitness','HEALTH AND FITNESS'],['Social Media','SOCIAL MEDIA'],['Hobbit','HOBBIT']]
	
	TECH = [['Android','ANDROID'],['Chrome','CHROME'],['Web','WEB'],['Iphone','IPHONE'],
	['Slack','SLACK'],['Mac','MAC'],['Hardware','HARDWARE'],['Virtual Reality','VIRTUAL REALITY'],
	['Email','EMAIL'],['IPad','IPAD'],['Windows','WINDOWS'],['Linux','LINUX'],
	['Developer Tools','DEVELOPER TOOLS'],['Extensions','EXTENSIONS']]
	
	GAMES = [['Virtual Reality','VIRTUAL REALITY'],['IPad','IPAD'],['Indie Games','INDIE GAMES'],
	['Occulus Rift','OCCULUS RIFT']]
	
	BOOKS = [['Food','FOOD'],['Music','MUSIC'],['Politics','POLITICS'],['Art','ART'],['Travel','TRAVEL'],
	['Music','MUSIC'],['Business','BUSINESS'],['Health and Fitness','HEALTH AND FITNESS'],
	['Social Media','SOCIAL MEDIA'],['Daredevil', 'DAREDEVIL']]
	
	PODCASTS = [['Food','FOOD'],['Music','MUSIC'],['Politics','POLITICS'],['Art','ART'],['Travel','TRAVEL'],
	['Music','MUSIC'],['Business','BUSINESS'],['Health and Fitness','HEALTH AND FITNESS'],
	['Social Media','SOCIAL MEDIA']]
	
	

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :find_product, only: [:edit, :update, :show, :upvote, :destroy]
	before_action :authenticate_user!, except: [:show, :browse_products, :index]
	before_action :authorised_user, only: [:edit, :update, :destroy]

	def new
		@product = current_user.products.new
	end
	
	def create
		@product = current_user.products.new(product_params)
		if @product.save
			redirect_to root_url
		else
			render 'new'
		end
	end
	
	 def browse_products
	 	@products = Product.all.search_products(params[:search]).paginate(:per_page => 12, :page => params[:page])
	  end
	
	def index
		@products = Product.all
	end
	
	def edit
	end
	
	def update
		if @product.update_attributes(product_params)
			redirect_to root_url
		else
			render 'edit'
		end
	end
	
	def show
		@comments = @product.comments
		@comment = Comment.new
	end
	
	def destroy
		@product.destroy
		redirect_to root_url
	end
	
	def upvote
		if current_user.voted_up_on? @product
			@product.downvote_from current_user
			redirect_to request.referrer
		else
			@product.upvote_from current_user
			redirect_to request.referrer
		end
	end
	
	def authorised_user
		redirect_to @product if @product.user_id != current_user.id
	end
	
	def find_product
		@product = Product.find(params[:id])
	end
	
	def product_params
		params.require(:product).permit(:title, :description, :link, :product_type, :image)
	end

end

app/helpers/products_helper.rb
module ProductsHelper

	def owned?(product)
		current_user.id == product.user_id
	end

end

app/views/products/_form.html.erb
<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@product) do |f| %>

			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>
		  
			<%= f.label :description %>
			<%= f.text_field :description, class: "form-control" %>
		
			<%= f.label :link %>
			<%= f.text_field :link, class: "form-control" %>
			
			<%= f.label :product_type, class: "form-product-type" %>
			<%= f.select :product_type, options_for_select(Product::TYPES, @product.product_type) %>
			
			<%= f.label :image %>
			<%= f.file_field :image, class: "form-control" %>
		 
		 	<% if current_page?(controller: 'products', action: 'new') %>
				<%= f.submit  "Create Product", class: "btn btn-primary", data: {disable_with: "Creating..."} %> 
			<% else current_page?(controller: 'products', action: 'edit') %>
				<%= f.submit  "Edit Product", class: "btn btn-primary", data: {disable_with: "Updating..."} %>
			<% end %>
		  
		<% end %>
	</div>
</div>

app/views/products/_product.html.erb
<%= link_to(product) do %>
				
	<div class = "product-section group">
	
		<%= image_tag(product.image_url, class: "product-sect-img") %>
		<div class = "product-sect-info">
			<h3 class = "product-sect-title"><%= product.title %></h3>
			<p class = "product-sect-descript">
				<%= product.description %>
			</p>
	
			<div class = "product-options group">
				<div class = "upvote">
					<%= image_tag('upvote1.png', class: "upvote-img") %>
							<%= link_to upvote_product_path(product), class: "upvotes", method: :put do %>
								<button class = "upvote-button" type = "button">
									<%= product.get_upvotes.size %>
								</button>
							<% end %>
				</div>
				<div class = "comments">
					<%= image_tag('comment-icon.png', class: "comment-icon") %>
					<p class ="comments-size"><%= product.comments.size %></p>
				</div>
				<div class = "add-collection">
					<img class = "add-collecton-icon">
					<span class = "add-collection-save">save</span>
				</div>
				<div class = "link">
					<%= image_tag('link.png', class: "link-icon" ) %>
				</div>
				<div class = "type">
				<%= product.product_type %>
				</div>
			</div>
		</div>
						

	</div>

<% end %>

app/views/products/browse_products.html.erb
<div class = "browse-header" >
	<ul class = "browse-header-nav">
		<li class = "browse-header-li">Products</li>
		<li class = "browse-header-li">Collections</li>
		<li class = "browse-header-li">Users</li>
	</ul>
</div>

<% @products.each do |product| %>
	<%= render product %>
<% end %>

app/views/products/edit.html.erb
<div class = "form-wrapper">

	<h1 class = "form-title">Edit Product</h1>

	<%= render 'form' %>

</div>

app/views/products/index.html.erb
<%= link_to "Logout", destroy_user_session_path, :method => :delete  %>
<h1>Products</h1>

<%= render @products %>

app/views/products/new.html.erb
<div class = "form-wrapper">

	<h1 class = "form-title">New Product</h1>

	<%= render 'form' %>

</div>

app/views/products/show.html.erb
<div class = "show-product">
	<div class = "show-product-info">
		<%= render @product %>
	</div>
	
	<% if user_signed_in? %>
		<% if owned?(@product) %>
			<%= link_to "Delete Product", @product, method: :delete, data: {confirm: "You sure?"} %>
			<%= link_to "Edit Product", edit_product_path(@product) %>
		<% end %>
	<% end %>

	<div class = "show-comments">
		
		<div class = "show-comments-all">
			<%= render 'comments/form' %>
			<%= render 'comments/comments' %>
		</div>
	</div>
</div>