config/routes.rb
Rails.application.routes.draw do

	 root 'static_pages#home'
	 get 'browse_products' => 'products#browse_products'
	 get 'popular' => 'static_pages#popular'
	 get 'tech' => 'categories#tech'
	 get 'games' => 'categories#games'
	 get 'books' => 'categories#books'
	 get 'podcasts' => 'categories#podcasts'
	 get 'tech/popular' => 'categories#popular_tech'
	 get 'games/popular' => 'categories#popular_games'
	 get 'books/popular' => 'categories#popular_books'
	 get 'podcasts/popular' => 'categories#popular_podcasts'
	 
	 
	 devise_for :users
	 resources :products do
	 	resources :comments, only: [:new, :create, :index]
	 	member do
	 		put "upvote" => "products#upvote"
	 	end
	 end
	 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Product Hunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class = "header group">
	
		
		<%= link_to image_tag('logo.png', class: "logo" ), root_path %>
	

		<%= form_tag browse_products_path, :method => 'get', class: "search" do %>
			<%= text_field_tag :search, params[:search], :style => "width: 275px; height: 25px;", class: "search-text", :placeholder => "Discover your next favourite thing..." %>
		<% end %>
	
		
		<div class = "header-right" >
			
		
			<% if user_signed_in? %>
					<%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "logout" %>
					<a href = "">
						<%= link_to image_tag(current_user.avatar, class: "profile-pic") %>
					</a>
			<% else %>	
					<div class = "logged-out-dropdown">...
						<div class = "dropdown-content">
							<a href = ""></a>
							<a href = ""></a>
							<a href = ""></a>
							<a href = ""></a>
							<a href = ""></a>
							<a href = ""></a>
							<a href = ""></a>
							<a href = ""></a>
							<a href = ""></a>
						</div>
					</div>
				<%= link_to "Login", user_session_path, class: "login" %>
			<% end %>
 			
 			
		</div>
		
	</header>


<%= yield %>

</body>
</html>